In [ ]:
!pip3 install tensorflow_text>=2.0.0rc0

In [ ]:
import tensorflow_hub as hub
import numpy as np
import tensorflow_text

In [ ]:
embed = hub.load("https://tfhub.dev/google/universal-sentence-encoder-multilingual/3")

In [ ]:
# Some texts of different lengths.
english_sentences = ["dog", "Puppies are nice.", "I enjoy taking long walks along the beach with my dog."]
italian_sentences = ["cane", "I cuccioli sono carini.", "Mi piace fare lunghe passeggiate lungo la spiaggia con il mio cane."]
japanese_sentences = ["犬", "子犬はいいです", "私は犬と一緒にビーチを散歩するのが好きです"]


# Compute embeddings.
en_result = embed(english_sentences)
it_result = embed(italian_sentences)
ja_result = embed(japanese_sentences)

# Compute similarity matrix. Higher score indicates greater similarity.
similarity_matrix_it = np.inner(en_result, it_result)
similarity_matrix_ja = np.inner(en_result, ja_result)

In [ ]:
similarity_matrix_ja

array([[0.9171357 , 0.511527  , 0.3158718 ],
       [0.44313598, 0.658635  , 0.309213  ],
       [0.2665054 , 0.25377458, 0.7672992 ]], dtype=float32)

In [ ]:
sent1 = "Football is fantastic sport, you just kick and run"
sent2 = "running is great for your health"
sent3 = "I don't like to move. I am a couch potato"

embs = embed([sent1, sent2, sent3])
embs

<tf.Tensor: shape=(3, 512), dtype=float32, numpy=
array([[-0.01043565,  0.0397465 ,  0.04154658, ..., -0.01284844,
         0.0261252 , -0.05097636],
       [-0.033679  , -0.05046516,  0.00164147, ...,  0.02319673,
        -0.02080888, -0.04610538],
       [-0.03822121, -0.00328445,  0.03299889, ..., -0.02711695,
         0.01458611,  0.06353468]], dtype=float32)>

In [ ]:
sent_pl_1 = "Lubię biegać za piłką. Piłka nożna to moja pasja."
sent_pl_2 = "Myj ręce, dzięki temu może będziesz zdrowy"
sent_en_1 = "I like football. This is my passion"
sent_en_2 = "Where is my friend. I feel very lonely"

In [ ]:
pl_embeddings = embed([sent_pl_1, sent_pl_2])
en_embeddings = embed([sent_en_1, sent_en_2])

In [ ]:
np.inner(pl_embeddings, en_embeddings)

array([[0.63552463, 0.11522794],
       [0.15198234, 0.15235355]], dtype=float32)